# Generated by Django 2.1 on 2018-09-10 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_text', models.CharField(max_length=1000)),
                ('complaint_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('DSN', models.IntegerField()),
                ('rank', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Officer'),
        ),
    ]
