# Generated by Django 2.1 on 2018-10-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='id',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='id',
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_nature',
            field=models.CharField(default='nature', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='district',
            field=models.CharField(default='district', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='file_no',
            field=models.CharField(default='fileno', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='officer',
            name='DSN',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
