# Generated by Django 2.1 on 2018-10-17 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20181017_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint_date',
            new_name='date',
        ),
    ]
