# Generated by Django 2.1 on 2018-11-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20181018_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_nature',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_text',
            field=models.CharField(max_length=10000),
        ),
    ]
