# Generated by Django 2.1 on 2018-12-05 03:03

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_complaint_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='latlng',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0,0), srid=4326),
        ),
    ]
