# Generated by Django 2.1 on 2018-12-05 03:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_complaint_latlng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='latlng',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
